name    'rossigee/smtpsandbox'
version '0.1.2'
source 'https://github.com/rossigee/rossigee-smtpsandbox'
author 'Ross Golder'
license 'GPL'
summary 'A postfix setup that captures all outbound mail.'
description 'A module to set up a postfix instance that captures all outbound mail to a mailbox, except where whitelisted.'
project_page 'https://github.com/rossigee/rossigee-smtpsandbox'
